### PR TITLE
Few features

### PR DESCRIPTION
**Pull request by adroitandroid**
- Removing dependency from activity, any context can be passed now which means even within services, Salut can be used
- SalutDevice is Parcelable now, so discovered devices can be passed in bundles for use elsewhere
- Serializer abstract method gives flexibility to use any serialization library now, dependency on LoganSquare removed
- Dependency on Apache IOUtils removed, replaced with better performing native java API (check SO comment)

-> Salut.java hasn't been changed much apart from the abstract method for serialization, it shows the entire file changed since file encoding has been changed

### CODE REVIEW

**Comment by neatorobito** [comment]
Thank you for your work. I will push a release in a bit.

**Comment by abselt** [comment]
after `public abstract class Salut`

call not work
`
            Salut network = new Salut(dataReceiver, serviceData, new SalutCallback() {
                @Override
                public void call() {
                }
            });`

**Comment by adroitandroid** [comment]
Right, you'll have to implement the serialize method to use the serializer
library of your choice

**Comment by abselt** [comment]
thanks
im not too much into java i lerned android directly
do i need to convert my activity to abstract also and will that cause a danger to other code or app perfurmance
counsidering that i will keep using the default serializer

**Comment by adroitandroid** [comment]
When your Android studio complaints about unimplemented, implement it and
since you're using LoganSquare, you'll need to return
LoganSquare.serialize(<method's argument>) within it

**Comment by abselt** [comment]
still cant understand how to make things right way thank you any way i will stick to my previous copy of the lib untel i learn that serialize thing 
but i hope you take a look at issue #29 may you  help us Im sure every one is facing this

**Comment by adroitandroid** [comment]
@markrjr is there code for a sample app in which I can show the new implementation
@abselt I'm not sure what the problem in #29 is, I had tried the underlying Android APIs directly before and for me they were unstable because they didn't guarantee discovery. That's when I came up with my own library [Near](https://github.com/adroitandroid/Near), that doesn't rely on the Android APIs at all

**Comment by abselt** [comment]
you are right it is more due to android API not this lib but still for example there is many actions in broadcast receiver for WIFI-direct are not implemented here i tried to make use of them but didnt make it alot better.

**Pull request merged**
