### PR TITLE
Add extra data to serviceData

### PR DESCRIPTION
**Pull request by deathslocus**

### CODE REVIEW

**Comment by neatorobito** [comment]
Why exactly the removal of the auto group creation?

**Comment by deathslocus** [comment]
Sorry I changed the master branch after the PR. 1d8db16 is the proper commit for this PR

**Comment by neatorobito** [comment]
Does this still work without creating the group on the devices you tested on? I noticed that you took that block out.

**Comment by deathslocus** [comment]
Yeah everything works fine, I just moved the group creation so it wasn't started immediately and could be initiated through a call

**Pull request merged**
